Docker 2
Otus-DevOps-2022-05/klimenko-sergey_microservices pull request #1
Opened 2022-08-11 08:33 UTC by klimenko-sergey

# Выполнено ДЗ "Технология контейнеризации. Введение в Docker"

 - [+] Основное ДЗ
 - [-] Задание со *

## В процессе сделано:
 - Запущены различные docker контейнеры
 - Изучены методы управления docker образами и контейнерами
 - Создан образ из docker контейнера, взятого с Docker Hub
 - Установлен инструмент docker-machine
 - Создана ВМ в Яндекс Облаке с docker host
 - Написан Dockerfile, а также все необходимые файлы конфигурации, скрипт
 - Создан образ:
   ```
   docker build -t reddit:latest .
   ```
 - Запущен контейнер:
   ```
   docker run --name reddit -d --network=host reddit:latest
   ```
 - Загружен образ на Docker Hub:
   ```
   docker tag reddit:latest klsergey/otus-reddit:1.0
   docker push klsergey/otus-reddit:1.0
   ```

## Как запустить проект:
 - Выполнить команду:
   ```
   docker run --name reddit -d -p 9292:9292 klsergey/otus-reddit:1.0
   ```

## Как проверить работоспособность:
 - Перейти по ссылке:
 [http://localhost:9292](http://localhost:9292)

## PR checklist
 - [-] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2022-08-11 19:41 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Не хватает некоторых файлов
Так же у вас не похоже не запускается приложение
Возникли какие то проблемы со сборкой?

2022-08-12 08:13 UTC, klimenko-sergey commented
@mrgreyves , добрый день!
В моей сборке имеется проблема - Puma сервис не стартует, указываются ошибки:
```
$ sudo docker logs reddit
about to fork child process, waiting until server is ready for connections.
forked process: 9
child process started successfully, parent exiting
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 2.5.1-p57) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 32
/reddit/helpers.rb:4: warning: redefining `object_id' may cause serious problems
! Unable to load application: NameError: uninitialized constant Mongo::Client
/reddit/app.rb:11:in `block in <top (required)>': uninitialized constant Mongo::Client (NameError)
        from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1427:in `configure'
        from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1919:in `block (2 levels) in delegate'
        from /reddit/app.rb:10:in `<top (required)>'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from config.ru:1:in `block in <main>'
        from /var/lib/gems/2.5.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        from /var/lib/gems/2.5.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        from /var/lib/gems/2.5.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        from /var/lib/gems/2.5.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
        from /var/lib/gems/2.5.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
        from /usr/local/bin/puma:23:in `load'
        from /usr/local/bin/puma:23:in `<main>'
```

2022-08-15 07:27 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к вашему докерфайлу
ПР пока закрою что бы он "не мешался"
Возникнут дополнительные вопросы, переоткройте пр =)

2022-08-15 07:27 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +RUN apt-get install -y mongodb-server ruby-full ruby-dev build-essential git
Попробуйте заменить строчку на
RUN apt-get update && \
    apt-get install -y mongodb ruby-full ruby-bundler build-essential git && \
    rm -rf /var/lib/apt/lists/*

2022-08-15 07:27 UTC, mrgreyves commented on docker-monolith/Dockerfile
> +RUN gem install bundler
Эту строчку стоит попробовать удалить =)

2022-08-15 10:21 UTC, klimenko-sergey commented on docker-monolith/Dockerfile
> +RUN gem install bundler
Сработало, благодарю!

2022-08-17 17:47 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-08-18 05:24 UTC, merged